### ISSUE TITLE
能否支持最新版本的Ueditor

### ISSUE THREAD

**Issue by JmonkeyGod** [akof1314/Wiz.UEditor#5]
能不能把Ueditor的版本升级下呢？目前版本已经低两个大版本了

**Comment by akof1314** [comment]
大版本改动的比较大，升级需要比较多的时间，后面有时间再进行升级。

**Comment by JmonkeyGod** [comment]
我上个星期试了一下，把最新版本的UEditor替换进去，发现增加保存按钮后无法保存，而且图片上传插件不可以使用(没有部署后端服务器)

**Comment by akof1314** [comment]
@JmonkeyGod 近期我再尝试下升级

**Comment by akof1314** [comment]
@JmonkeyGod 貌似官方团队没有再维护了，暂缓跟进。

**Comment by akof1314** [comment]
@JmonkeyGod 已升级，试试看。
