### ISSUE TITLE
Tab鍵問題

### ISSUE THREAD

**Issue by Gbuntoo** [akof1314/Wiz.UEditor#8]
在編輯模式中無法使用Tab，而用方向鍵或鼠標的效率是極low的...所以請問：
編輯模式中如果我想從H1將焦點切換到下一個H是否有啥敲門？

**Comment by akof1314** [comment]
@Gbuntoo 无法使用Tab，因为被为知程序给拦截了，后面可以加个替换其他键来实现tab功能。

暂时不知道快速切换H1的方法~

**Comment by Gbuntoo** [comment]
@akof1314  收到 並表示感謝
